//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace CapGUI.serverXML {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfXElement", Namespace="http://schemas.datacontract.org/2004/07/System.Xml.Linq", ItemName="XElement")]
    public class ArrayOfXElement : System.Collections.ObjectModel.ObservableCollection<System.Xml.Linq.XElement> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serverXML.IXmlWebService")]
    public interface IXmlWebService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IXmlWebService/GetXmlData", ReplyAction="http://tempuri.org/IXmlWebService/GetXmlDataResponse")]
        System.IAsyncResult BeginGetXmlData(string xmlUrl, System.AsyncCallback callback, object asyncState);
        
        CapGUI.serverXML.ArrayOfXElement EndGetXmlData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXmlWebServiceChannel : CapGUI.serverXML.IXmlWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetXmlDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetXmlDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CapGUI.serverXML.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CapGUI.serverXML.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XmlWebServiceClient : System.ServiceModel.ClientBase<CapGUI.serverXML.IXmlWebService>, CapGUI.serverXML.IXmlWebService {
        
        private BeginOperationDelegate onBeginGetXmlDataDelegate;
        
        private EndOperationDelegate onEndGetXmlDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetXmlDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public XmlWebServiceClient() {
        }
        
        public XmlWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XmlWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetXmlDataCompletedEventArgs> GetXmlDataCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CapGUI.serverXML.IXmlWebService.BeginGetXmlData(string xmlUrl, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetXmlData(xmlUrl, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapGUI.serverXML.ArrayOfXElement CapGUI.serverXML.IXmlWebService.EndGetXmlData(System.IAsyncResult result) {
            return base.Channel.EndGetXmlData(result);
        }
        
        private System.IAsyncResult OnBeginGetXmlData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string xmlUrl = ((string)(inValues[0]));
            return ((CapGUI.serverXML.IXmlWebService)(this)).BeginGetXmlData(xmlUrl, callback, asyncState);
        }
        
        private object[] OnEndGetXmlData(System.IAsyncResult result) {
            CapGUI.serverXML.ArrayOfXElement retVal = ((CapGUI.serverXML.IXmlWebService)(this)).EndGetXmlData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetXmlDataCompleted(object state) {
            if ((this.GetXmlDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetXmlDataCompleted(this, new GetXmlDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetXmlDataAsync(string xmlUrl) {
            this.GetXmlDataAsync(xmlUrl, null);
        }
        
        public void GetXmlDataAsync(string xmlUrl, object userState) {
            if ((this.onBeginGetXmlDataDelegate == null)) {
                this.onBeginGetXmlDataDelegate = new BeginOperationDelegate(this.OnBeginGetXmlData);
            }
            if ((this.onEndGetXmlDataDelegate == null)) {
                this.onEndGetXmlDataDelegate = new EndOperationDelegate(this.OnEndGetXmlData);
            }
            if ((this.onGetXmlDataCompletedDelegate == null)) {
                this.onGetXmlDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetXmlDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetXmlDataDelegate, new object[] {
                        xmlUrl}, this.onEndGetXmlDataDelegate, this.onGetXmlDataCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CapGUI.serverXML.IXmlWebService CreateChannel() {
            return new XmlWebServiceClientChannel(this);
        }
        
        private class XmlWebServiceClientChannel : ChannelBase<CapGUI.serverXML.IXmlWebService>, CapGUI.serverXML.IXmlWebService {
            
            public XmlWebServiceClientChannel(System.ServiceModel.ClientBase<CapGUI.serverXML.IXmlWebService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetXmlData(string xmlUrl, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = xmlUrl;
                System.IAsyncResult _result = base.BeginInvoke("GetXmlData", _args, callback, asyncState);
                return _result;
            }
            
            public CapGUI.serverXML.ArrayOfXElement EndGetXmlData(System.IAsyncResult result) {
                object[] _args = new object[0];
                CapGUI.serverXML.ArrayOfXElement _result = ((CapGUI.serverXML.ArrayOfXElement)(base.EndInvoke("GetXmlData", _args, result)));
                return _result;
            }
        }
    }
}
