//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace CapGUI.robotService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="robotService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/SetStatus", ReplyAction="http://tempuri.org/IService/SetStatusResponse")]
        System.IAsyncResult BeginSetStatus(string state, System.AsyncCallback callback, object asyncState);
        
        void EndSetStatus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/SetCode", ReplyAction="http://tempuri.org/IService/SetCodeResponse")]
        System.IAsyncResult BeginSetCode(string code, System.AsyncCallback callback, object asyncState);
        
        void EndSetCode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetStatus", ReplyAction="http://tempuri.org/IService/GetStatusResponse")]
        System.IAsyncResult BeginGetStatus(System.AsyncCallback callback, object asyncState);
        
        string EndGetStatus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetCode", ReplyAction="http://tempuri.org/IService/GetCodeResponse")]
        System.IAsyncResult BeginGetCode(System.AsyncCallback callback, object asyncState);
        
        string EndGetCode(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CapGUI.robotService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CapGUI.robotService.IService>, CapGUI.robotService.IService {
        
        private BeginOperationDelegate onBeginSetStatusDelegate;
        
        private EndOperationDelegate onEndSetStatusDelegate;
        
        private System.Threading.SendOrPostCallback onSetStatusCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetCodeDelegate;
        
        private EndOperationDelegate onEndSetCodeDelegate;
        
        private System.Threading.SendOrPostCallback onSetCodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStatusDelegate;
        
        private EndOperationDelegate onEndGetStatusDelegate;
        
        private System.Threading.SendOrPostCallback onGetStatusCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCodeDelegate;
        
        private EndOperationDelegate onEndGetCodeDelegate;
        
        private System.Threading.SendOrPostCallback onGetCodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SetStatusCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SetCodeCompleted;
        
        public event System.EventHandler<GetStatusCompletedEventArgs> GetStatusCompleted;
        
        public event System.EventHandler<GetCodeCompletedEventArgs> GetCodeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CapGUI.robotService.IService.BeginSetStatus(string state, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetStatus(state, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CapGUI.robotService.IService.EndSetStatus(System.IAsyncResult result) {
            base.Channel.EndSetStatus(result);
        }
        
        private System.IAsyncResult OnBeginSetStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string state = ((string)(inValues[0]));
            return ((CapGUI.robotService.IService)(this)).BeginSetStatus(state, callback, asyncState);
        }
        
        private object[] OnEndSetStatus(System.IAsyncResult result) {
            ((CapGUI.robotService.IService)(this)).EndSetStatus(result);
            return null;
        }
        
        private void OnSetStatusCompleted(object state) {
            if ((this.SetStatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetStatusAsync(string state) {
            this.SetStatusAsync(state, null);
        }
        
        public void SetStatusAsync(string state, object userState) {
            if ((this.onBeginSetStatusDelegate == null)) {
                this.onBeginSetStatusDelegate = new BeginOperationDelegate(this.OnBeginSetStatus);
            }
            if ((this.onEndSetStatusDelegate == null)) {
                this.onEndSetStatusDelegate = new EndOperationDelegate(this.OnEndSetStatus);
            }
            if ((this.onSetStatusCompletedDelegate == null)) {
                this.onSetStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetStatusCompleted);
            }
            base.InvokeAsync(this.onBeginSetStatusDelegate, new object[] {
                        state}, this.onEndSetStatusDelegate, this.onSetStatusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CapGUI.robotService.IService.BeginSetCode(string code, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetCode(code, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CapGUI.robotService.IService.EndSetCode(System.IAsyncResult result) {
            base.Channel.EndSetCode(result);
        }
        
        private System.IAsyncResult OnBeginSetCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string code = ((string)(inValues[0]));
            return ((CapGUI.robotService.IService)(this)).BeginSetCode(code, callback, asyncState);
        }
        
        private object[] OnEndSetCode(System.IAsyncResult result) {
            ((CapGUI.robotService.IService)(this)).EndSetCode(result);
            return null;
        }
        
        private void OnSetCodeCompleted(object state) {
            if ((this.SetCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetCodeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetCodeAsync(string code) {
            this.SetCodeAsync(code, null);
        }
        
        public void SetCodeAsync(string code, object userState) {
            if ((this.onBeginSetCodeDelegate == null)) {
                this.onBeginSetCodeDelegate = new BeginOperationDelegate(this.OnBeginSetCode);
            }
            if ((this.onEndSetCodeDelegate == null)) {
                this.onEndSetCodeDelegate = new EndOperationDelegate(this.OnEndSetCode);
            }
            if ((this.onSetCodeCompletedDelegate == null)) {
                this.onSetCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetCodeCompleted);
            }
            base.InvokeAsync(this.onBeginSetCodeDelegate, new object[] {
                        code}, this.onEndSetCodeDelegate, this.onSetCodeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CapGUI.robotService.IService.BeginGetStatus(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStatus(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CapGUI.robotService.IService.EndGetStatus(System.IAsyncResult result) {
            return base.Channel.EndGetStatus(result);
        }
        
        private System.IAsyncResult OnBeginGetStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CapGUI.robotService.IService)(this)).BeginGetStatus(callback, asyncState);
        }
        
        private object[] OnEndGetStatus(System.IAsyncResult result) {
            string retVal = ((CapGUI.robotService.IService)(this)).EndGetStatus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStatusCompleted(object state) {
            if ((this.GetStatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStatusCompleted(this, new GetStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStatusAsync() {
            this.GetStatusAsync(null);
        }
        
        public void GetStatusAsync(object userState) {
            if ((this.onBeginGetStatusDelegate == null)) {
                this.onBeginGetStatusDelegate = new BeginOperationDelegate(this.OnBeginGetStatus);
            }
            if ((this.onEndGetStatusDelegate == null)) {
                this.onEndGetStatusDelegate = new EndOperationDelegate(this.OnEndGetStatus);
            }
            if ((this.onGetStatusCompletedDelegate == null)) {
                this.onGetStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStatusCompleted);
            }
            base.InvokeAsync(this.onBeginGetStatusDelegate, null, this.onEndGetStatusDelegate, this.onGetStatusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CapGUI.robotService.IService.BeginGetCode(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCode(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CapGUI.robotService.IService.EndGetCode(System.IAsyncResult result) {
            return base.Channel.EndGetCode(result);
        }
        
        private System.IAsyncResult OnBeginGetCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CapGUI.robotService.IService)(this)).BeginGetCode(callback, asyncState);
        }
        
        private object[] OnEndGetCode(System.IAsyncResult result) {
            string retVal = ((CapGUI.robotService.IService)(this)).EndGetCode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCodeCompleted(object state) {
            if ((this.GetCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCodeCompleted(this, new GetCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCodeAsync() {
            this.GetCodeAsync(null);
        }
        
        public void GetCodeAsync(object userState) {
            if ((this.onBeginGetCodeDelegate == null)) {
                this.onBeginGetCodeDelegate = new BeginOperationDelegate(this.OnBeginGetCode);
            }
            if ((this.onEndGetCodeDelegate == null)) {
                this.onEndGetCodeDelegate = new EndOperationDelegate(this.OnEndGetCode);
            }
            if ((this.onGetCodeCompletedDelegate == null)) {
                this.onGetCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCodeCompleted);
            }
            base.InvokeAsync(this.onBeginGetCodeDelegate, null, this.onEndGetCodeDelegate, this.onGetCodeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CapGUI.robotService.IService CreateChannel() {
            return new ServiceClientChannel(this);
        }
        
        private class ServiceClientChannel : ChannelBase<CapGUI.robotService.IService>, CapGUI.robotService.IService {
            
            public ServiceClientChannel(System.ServiceModel.ClientBase<CapGUI.robotService.IService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSetStatus(string state, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = state;
                System.IAsyncResult _result = base.BeginInvoke("SetStatus", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSetStatus(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SetStatus", _args, result);
            }
            
            public System.IAsyncResult BeginSetCode(string code, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = code;
                System.IAsyncResult _result = base.BeginInvoke("SetCode", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSetCode(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SetCode", _args, result);
            }
            
            public System.IAsyncResult BeginGetStatus(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetStatus", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetStatus(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetStatus", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCode(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCode", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetCode(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetCode", _args, result)));
                return _result;
            }
        }
    }
}
